[package]
name = "get_all_info"
version = "0.1.0"
authors = ["Andrew Chin <achin@eminence32.net>"]

[dependencies]
lifx-core = {path =  "../../lifx-core"}
get_if_addrs = "0.5.3"
failure = "0.1.2"
chrono = "0.4.6"